#!/usr/bin/env node

require('babel-register')()
require('app-module-path').addPath(require('path').resolve(__dirname))

const program = require('commander')
const { version } = require('core/vulcan')
const { start } = require('core/commands')
program.version(version)

program.command('start')
  .alias('serve')
  .description('Start your Vulcan app')
  .option('-p, --port <int>', 'The port on which the app will be running', process.env.PORT || 1337)
  .action(start())

program.parse(process.argv)

if (!program.args.length) {
  program.help()
}
