#!/usr/bin/env node

require('babel-core/register')()
require('app-module-path').addPath(require('path').resolve(__dirname))

const program = require('commander')
const { db } = require('core/bookshelf')
const commands = require('core/commands')
program.version(require('core/vulcan').version, '-v, --version')

commands.map((cmd) => {
  const command = program.command(cmd.command)
  command.description(cmd.description)
  if (cmd.options) {
    cmd.options.map((opt) => command.option(opt.flags, opt.description, opt.default))
  }
  command.action(cmd.action(db.destroy))
})

program.parse(process.argv)

if (!program.args.length) {
  program.help()
}
